/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class main_ActiveWindowName */

#ifndef _Included_main_ActiveWindowName
#define _Included_main_ActiveWindowName
#ifdef __cplusplus
extern "C" {
#endif
	/*
	* Class:     main_ActiveWindowName
	* Method:    getActiveWindowName
	* Signature: ()Ljava/lang/String;
	*/
	JNIEXPORT jstring JNICALL Java_main_ActiveWindowName_getActiveWindowName
	(JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
